version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'bvRH'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - type: bind
        source: "/home/douglas/Documents/ArquivosDouglas/Docker/MySqlDbSistemaBahiaVisual"
        target: /var/lib/mysql
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
