version: '3.1'

services:
  db_bvRH:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'bvRH'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "/home/douglasbv/Documentos/Douglas Pessoal/BancoDeDados/Docker/MySqlDbRhBv:/var/lib/mysql"
    networks:
      - docker-network

  db_comprasBV:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'comprasBV'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - "/home/douglasbv/Documentos/Douglas Pessoal/BancoDeDados/Docker/MySqlDbComprasBv:/var/lib/mysql"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
