#port config
server:
  port: 8090

spring:
  application:
    name: "apiRH"

#dataBase config
datasource:
  url: jdbc:mysql://localhost:3306/rhApi_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
  username: "root"
  password: "bv32582018"
  driver-class-name: "com.mysql.cj.jdbc.Driver"

jpa:
  hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  hibernate.ddl-auto: update
  hibernate:
    jdbc: time_zone = TimeZone
  show-sql: true

#devtools config
devtools:
  restart:
    enabled: true

#swagger config
springdoc:
  swagger-ui:
    path: "apiRH/swagger-ui.html"
